version: '3.1'

services:
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: 'toor'
  mqtt:
    image: eclipse-mosquitto:1.5.5
    ports:
      - '1883:1883'
      - '9001:9001'
