apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt
  name: mqtt-external
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
  selector:
    app: mqtt
