apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
        - image: eclipse-mosquitto:1.5.5
          name: mqtt
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 9001
              name: mqtt-web-socket